CREATE TABLE wordlegroundhog (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT,
 word CHAR(5) NOT NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (id)
);