CREATE TABLE wordlewinnersv2 (
 id INT UNSIGNED NOT NULL AUTO_INCREMENT,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 date DATE NOT NULL,
 wordnumber INT NOT NULL,
 word CHAR(5) NOT NULL,
 PRIMARY KEY (id)
);