CREATE TABLE `words_winners` (
 `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
 `winners_words` VARCHAR(255) NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB
 DEFAULT CHARSET=utf8mb4
 COLLATE=utf8mb4_unicode_ci;